/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT hello.cdb */

/*  Include Header Files  */
#include <std.h>
#include <hst.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <sem.h>
#include <mbx.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern HST_Obj RTA_fromHost;
extern HST_Obj RTA_toHost;
extern SWI_Obj KNL_swi;
extern SWI_Obj SWI_Audio;
extern TSK_Obj TSK_idle;
extern TSK_Obj audioTSK;
extern TSK_Obj buttonTSK;
extern TSK_Obj fftTSK;
extern TSK_Obj lcdTSK;
extern LOG_Obj LOG_system;
extern LOG_Obj trace;
extern SEM_Obj SEM_i2c;
extern MBX_Obj audioMBX;
extern MBX_Obj fftMBX;
extern MBX_Obj lcdMBX;
extern STS_Obj IDL_busyObj;


#ifdef __cplusplus
}
#endif /* extern "C" */
